### ISSUE TITLE
All mutations must follow the following format X123Y for example: A78R!

### ISSUE THREAD

**Issue by Diogopell** [omarwagih/rmimp#9]
Hi

How should I input stop codons? X123* isn't working.
Also, just to make sure, indels are X, right?

Thanks!

**Comment by omarwagih** [comment]
Indels are not supported (since many of the effects are precomputed on all possible SNPs to provide immediate results). 

Stop codons are marked with *. X and Y were just used as placeholders. X is not a valid amino acid and therefore won’t be accepted.
